SET SERVEROUTPUT ON;

DECLARE
   A INT:= &A;
   B INT:= &B;
BEGIN
   FOR i IN A..B LOOP 
      DBMS_OUTPUT.PUT(I||' ');
    END LOOP;
    DBMS_OUTPUT.NEW_LINE();

END;
/

DECLARE 
    NUM INT:=&NUM;
    i INT:=1;
BEGIN
     WHILE I<=NUM LOOP
       IF MOD(NUM,I)=0 THEN 
          DBMS_OUTPUT.PUT(I||' ');
        END IF;
        i:=i+1;
    END LOOP;
    DBMS_OUTPUT.NEW_LINE();
END;
/



CREATE TABLE EMP(
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    AGE INT,
    SALARY INT,
    DEPARTMENT VARCHAR(50)
);

DROP TABLE EMP;

INSERT INTO EMP VALUES(1,'Alice',27,60000,'Testing');
INSERT INTO EMP VALUES(2,'Bob',36,70000,'Operations');
INSERT INTO EMP VALUES(3,'joe',42,80000,'HR');
INSERT INTO EMP VALUES(4,'Tim',37,43000,'Operations');
INSERT INTO EMP VALUES(5,'Hazel',33,69000,'Testing');
INSERT INTO EMP VALUES(6,'sophia',32,72000,'HR');
INSERT INTO EMP VALUES(7,'Genelia',41,59000,'Operations');

SELECT * FROM EMP;

--sum
SELECT SUM(SALARY) FROM EMP WHERE DEPARTMENT = 'HR';
SELECT SUM(SALARY) FROM EMP WHERE DEPARTMENT = 'Testing';

--min
SELECT MIN(SALARY)  AS MIN_SALARY FROM EMP WHERE DEPARTMENT = 'Operations';
SELECT MIN(SALARY) AS MIN_SALARY FROM EMP;

--MAX()
SELECT MAX(AGE) AS MAX_AGE FROM EMP;
SELECT MAX(AGE) AS EMP_MAX_AGE FROM EMP WHERE DEPARTMENT = 'HR';

--AVG()
SELECT AVG(SALARY) FROM EMP WHERE DEPARTMENT='HR';
SELECT AVG(SALARY) FROM EMP WHERE DEPARTMENT='Testing';

--COUNT()
SELECT COUNT(*) FROM EMP;
SELECT COUNT(*) FROM EMP WHERE DEPARTMENT = 'Operations';


--External  questionss

CREATE TABLE EXTERNAL(
   ID INT PRIMARY KEY,
   NAME VARCHAR(50) NOT NULL,
   AGE INT,
   GRADE VARCHAR(2)
);

INSERT INTO EXTERNAL VALUES(123,'PHIL SALT',35,'A');
INSERT INTO EXTERNAL VALUES(124,'KOHLI',34,'A+');
INSERT INTO EXTERNAL VALUES(125,'RAJAT',34,'S');
INSERT INTO EXTERNAL VALUES(128,'LIVINGSTONE',32,'A');
INSERT INTO EXTERNAL VALUES(126,'TIMDAVID',37,'A+');
INSERT INTO EXTERNAL VALUES(129,'JITESH',31,'S');

ALTER TABLE EXTERNAL ADD MARKS INT;





