-------------------------------------------------------------------------------- Select Queries;
--- SQL thinking process order
--1. FROM
--2. WHERE
--3. GROUP BY
--4. HAVING
--5. SELECT
--6. ORDER BY
--7. LIMIT
---------------- This is the order WHERE use before GROUP BY and HAVING after GROUP BY
--1. WHERE salary > 45000
--2. GROUP BY department
--3. HAVING COUNT(*) > 1

SELECT * FROM EMPLOYEE;
select NAME, AGE, SALARY AS jeetham from employee WHERE AGE > 30 OR SALARY BETWEEN 50000 AND 100000;
SELECT * FROM EMPLOYEE WHERE DEPARTMENT IN('Operations','SW') AND AGE BETWEEN 30 AND 40;
SELECT * FROM EMPLOYEE ORDER BY SALARY DESC;
SELECT * FROM EMPLOYEE ORDER BY SALARY DESC FETCH FIRST 3 ROWS ONLY;
SELECT DEPARTMENT, SUM(SALARY) FROM EMPLOYEE WHERE SALARY > 30000 GROUP BY DEPARTMENT HAVING SUM(SALARY) > 100000;
SELECT DEPARTMENT, AVG(SALARY) FROM EMPLOYEE GROUP BY DEPARTMENT HAVING SUM(SALARY)>1000000 AND COUNT(*)>10;
SELECT * FROM EMPLOYEE WHERE NAME LIKE 'S%';  SELECT * FROM EMPLOYEE WHERE NAME LIKE '%r'; SELECT * FROM EMPLOYEE WHERE NAME LIKE '__________';
SELECT DISTINCT(DEPARTMENT) FROM EMPLOYEE;

--Display the top 3 highest-paid employees.
SELECT * FROM EMPLOYEE WHERE SALARY IS NOT NULL ORDER BY SALARY DESC FETCH FIRST 3 ROWS ONLY;
--Display the number of employees in each department.
SELECT department, COUNT(*) FROM EMPLOYEE GROUP BY DEPARTMENT;
--**Display the highest salary in the company.
SELECT * FROM EMPLOYEE WHERE SALARY IS NOT NULL ORDER BY SALARY DESC FETCH FIRST 1 ROWS ONLY;
--**Display the second-highest salary.
SELECT * FROM EMPLOYEE WHERE SALARY < (
  SELECT SALARY FROM EMPLOYEE WHERE SALARY IS NOT NULL ORDER BY SALARY DESC FETCH FIRST 1 ROWS ONLY
) ORDER BY SALARY DESC FETCH FIRST 1 ROWS ONLY;
--**Display the names of employees earning more than the average salary.
SELECT NAME, SALARY FROM EMPLOYEE WHERE SALARY >(
SELECT AVG(SALARY) FROM EMPLOYEE
);
--**Display the department with the highest total salary.
SELECT DEPARTMENT,MAX(SALARY) FROM EMPLOYEE GROUP BY DEPARTMENT;\
--**Display the top 2 departments having the highest average salary.
SELECT DEPARTMENT, AVG(SALARY) FROM EMPLOYEE WHERE DEPARTMENT IS NOT NULL GROUP BY DEPARTMENT ORDER BY AVG(SALARY) DESC FETCH FIRST 2 ROWS ONLY;
--***Display departments having at least 2 employees whose salary is greater than 50000.
SELECT DEPARTMENT,COUNT(*) FROM EMPLOYEE WHERE SALARY > 80000 GROUP BY DEPARTMENT HAVING COUNT(*) > 0;



--------------------------------------------------------------------------------Insert and delete Queries
CREATE TABLE PREP1(
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    EMAIL VARCHAR(100),
);

SELECT * FROM PREP1;
INSERT INTO PREP1 VALUES(1,'VENTAKT','VENKAT@gmail.com');

INSERT INTO PREP1(ID,EMAIL) VALUES(3,'JITTU@GMAIL.COM');

DELETE FROM PREP1 WHERE ID = 1;

UPDATE PREP1 SET NAME = 'JITTU' WHERE ID = 3;

DESC PREP1;
--------------------------------------------------------------------------------ALTER QUERIES
ALTER TABLE PREP1 ADD SALARY NUMBER;
UPDATE PREP1 SET SALARY = 0;
ALTER TABLE PREP1 MODIFY SALARY NOT NULL;
ALTER TABLE PREP1 RENAME COLUMN SALARY TO EMP_SALARY;
ALTER TABLE PREP1 ADD DUMMY INT;
ALTER TABLE PREP1 DROP COLUMN DUMMY;
ALTER TABLE PREP1 ADD CONSTRAINT EMAIL_UK UNIQUE(EMAIL);   
