CREATE TABLE BAM(
   id INT,
   age INT,
   name VARCHAR(50),
   email VARCHAR(50),
   phn_number INT
);

ALTER TABLE BAM MODIFY ID INT PRIMARY KEY;
INSERT INTO BAM VALUES(1,19,'SRINIVAS','gkljads@1111gmail.com',9505691379);
INSERT INTO BAM VALUES(2,19,'Raj','rhjks@1111gmail.com',9515644579);
INSERT INTO BAM VALUES(3,29,'Sundar','kjherwjs@1111gmail.com',945646679);
INSERT INTO BAM VALUES(5,59,'Emily Brown','aueijdf@1111gmail.com',894895659);

UPDATE BAM SET AGE = 25 WHERE ID = 3;
UPDATE BAM SET EMAIL = 'Rahul@gmail.com' WHERE ID = 4;

SELECT * FROM BAM;


CREATE TABLE constrains(
     id INT UNIQUE,
     NAME VARCHAR(50) NOT NULL,
     age INT CHECK (age > 10),
     college VARCHAR(49) DEFAULT  'COLLEGE'
);

SELECT NAME FROM BAM INTERSECT SELECT NAME FROM EMPLOYEE;

SELECT FLOOR(MONTHS_BETWEEN(SYSDATE,'12-07-2020')) FROM DUAL; 

SELECT EXTRACT(MONTH FROM SYSDATE) FROM DUAL;

SELECT ADD_MONTHS(SYSDATE,3) FROM DUAL;

SELECT LAST_DAY(SYSDATE) FROM DUAL;

SELECT NEXT_DAY('22-9-2038','SUNDAY') FROM DUAL;

SELECT TO_CHAR(SYSDATE,'YYYY-MM:DD HH-MI-SS') FROM DUAL;

SET SERVEROUTPUT ON;
BEGIN 
   FOR i IN 1..10 LOOP
       DBMS_OUTPUT.PUT(i||' ');
   END LOOP;
       DBMS_OUTPUT.NEW_LINE();
END;
/

SELECT * FROM EMPLOYEE;

SELECT DEPARTMENT,COUNT(*), SUM(SALARY),CEIL(AVG(SALARY)) FROM EMPLOYEE GROUP BY DEPARTMENT;

SELECT name,department,MAX(SALARY) FROM EMPLOYEE WHERE SALARY>10000 GROUP BY DEPARTMENT HAVING MAX(SALARY)>30000;

SELECT department
FROM EMPLOYEE 
WHERE SALARY > 30000
GROUP BY DEPARTMENT HAVING MAX(SALARY)>40000;



SELECT CONCAT('LACINHCET',' BUH') AS CONCATINATION FROM DUAL;

SELECT UPPER('dsjoejie') FROM DUAL;
SELECT LOWER('dsjDIUejie') FROM DUAL;

SELECT LENGTH('QWERTYUIOP') FROM DUAL;

SELECT LTRIM('****JAOIEWJO','*') FROM DUAL;

SELECT RTRIM('*JAOJOWEJF-----','*-') FROM DUAL;

SELECT REPLACE('mADHUKAR SATYA SAI RAM','SATYA','AYTAS') FROM DUAL;

SELECT SUBSTR('TECHNICALHUB',1,9) FROM DUAL;

SELECT REVERSE('SAVINIRS') FROM DUAL;

SELECT INITCAP('venkat') FROM DUAL;

SELECT RPAD('Madhuka',15,'r') FROM dual;

SELECT ABS(-8394) AS abs, CEIL(-77.64) AS ceil, FLOOR(-77.56) AS FLOOR FROM DUAL;



SET SERVEROUTPUT ON;

DECLARE 
ID INT;
BEGIN 
ID:=&ID;
  IF MOD(ID,2)=0 THEN
     DBMS_OUTPUT.PUT_LINE('eVEN');
   END IF;
  
DBMS_OUTPUT.PUT_LINE(ID*2);

END;
/

DECLARE 

BEGIN 
      FOR I IN 1..10 LOOP
        DBMS_OUTPUT.PUT(i);
       END LOOP;
       DBMS_OUTPUT.NEW_LINE();
       
       
END;
/













